print("hello world")

print("Another printing line")
print("Another printing line")
print("Another printing line")
print("Another printing line")
print("Another printing line")
print("Another printing line")
print("Another printing line")
print("Another printing line")